# Generated by Django 3.1.7 on 2021-03-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210325_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['-post_date']},
        ),
    ]
